const recipes = [
  {
    id: 1,
    name: "Pizza",
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=500",
  },
  {
    id: 2,
    name: "Burger",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500",
  },
  {
    id: 3,
    name: "Pasta",
    image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=500",
  },
  {
    id: 4,
    name: "Salad",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500",
  },
];

function PopularRecipes() {
  return (
    <section className="popular-recipes">
      <h2>🔥 Popular Recipes</h2>
      <p className="popular-subtitle">
  Discover the most loved recipes generated by our AI.
</p>

      <div className="recipe-grid">
        {recipes.map((recipe) => (
          <div className="recipe-card" key={recipe.id}>
            <img src={recipe.image} alt={recipe.name} />
            <h3>{recipe.name}</h3>
          </div>
        ))}
      </div>
    </section>
  );
}

export default PopularRecipes;